steps:
  # Install backend dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    dir: 'server'

  # Build backend
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'server'

  # Install frontend dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    dir: '.'

  # Build frontend
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    dir: '.'

  # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['app', 'deploy', '--quiet']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: 1200s